### ISSUE TITLE
Style filter.

### ISSUE THREAD

**Issue by NigelDcruz** [NigelDcruz/covid-19#11]
Style the search country filter and button.

**Comment by ShubhamPandey-Engineer** [comment]
Hello `Sir,My` name is shubham .I too have created an web application  which shows current statistics of COVID-19 
https://indiacovid19stats.000webhostapp.com/
Can I contribute to this repository

**Comment by NigelDcruz** [comment]
Hi Shubham, thank you for your interest in this repo. This issue is completed and will be closed now. However, there are other open issues that you can contribute to. Please make the required changes and send a pull request. After a brief code review, your code will be merged.  Thank you.

**Comment by ShubhamPandey-Engineer** [comment]
Ok ,sir  I will do that

**Comment by ShubhamPandey-Engineer** [comment]
Sir ,how many more FAQ are need . a rough idea
